project:
  title: "computo-quarto-extension"
  render: 
    - computo-quarto-extension.qmd

title: "Computo Journal Format"
subtitle: "To be used as template for contribution to `Computo`"
date: 01/02/2023
date-modified: last-modified
author:
  - name: The Computo Team
    corresponding: true
    email: contact@computo-journal.org
    url: https://computo-journal.org
    orcid: 0000-0000-0000-0000
    affiliations:
      - name: Société Française de Statistique
        department: Statistique
        address: IHP
        city: Paris
        country: France
        postal-code: 75005
  - name: a friend
    affiliations:
      - Another Affiliation
keywords: [template, quarto, R, Python, reproductibility]
abstract: |
  This document provides a template based on the quarto system for contributions to Computo. The github repository in itself provides a specific quarto extension useful for authors (and editors!).
bibliography: references.bib
google-scholar: true
github-user: computorg
repo: "computo-quarto-extension"
status: published # one of: submitted, accepted, published
citation:
  type: article-journal
  container-title: "Computo"
  issn: "2824-7795"
  doi: "10.5072/computo.0000" # placeholder DOI (10.5072 is the official DOI test prefix), replace once assigned
format:
  computo-html: default
  computo-pdf: default

diagram:
  engine:
    tikz:
      header-includes:
        - '\usetikzlibrary{arrows}'

